--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMENTBOARD
--------------------------------------------------------

  CREATE TABLE "HR"."COMMENTBOARD" 
   (	"CNUM" NUMBER, 
	"MSG" VARCHAR2(500 BYTE), 
	"BNUM" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"REGDATE" VARCHAR2(20 BYTE) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."COMMENTBOARD_PK" ON "HR"."COMMENTBOARD" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMMENTBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."COMMENTBOARD" ADD CONSTRAINT "COMMENTBOARD_PK" PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."COMMENTBOARD" MODIFY ("CNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."COMMENTBOARD" ADD CONSTRAINT "COMMENTBOARD_FK1" FOREIGN KEY ("BNUM")
	  REFERENCES "HR"."BOARD" ("NUM") ENABLE;
