--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-4岿-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMBOARD
--------------------------------------------------------

  CREATE TABLE "HR"."COMBOARD" 
   (	"CNUM" NUMBER, 
	"MSG" VARCHAR2(500 BYTE), 
	"BNUM" NUMBER, 
	"USERID" VARCHAR2(50 BYTE), 
	"REGDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."COMBOARD_PK" ON "HR"."COMBOARD" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."COMBOARD" ADD CONSTRAINT "COMBOARD_PK" PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."COMBOARD" MODIFY ("CNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."COMBOARD" ADD CONSTRAINT "COMBOARD_FK1" FOREIGN KEY ("BNUM")
	  REFERENCES "HR"."SIMPLEBOARD" ("NUM") ENABLE;
  ALTER TABLE "HR"."COMBOARD" ADD CONSTRAINT "COMBOARD_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "HR"."MEMBERDB" ("USERID") ENABLE;
