--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-4岿-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SIMPLEBOARD
--------------------------------------------------------

  CREATE TABLE "HR"."SIMPLEBOARD" 
   (	"NUM" NUMBER, 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"REGDATE" VARCHAR2(20 BYTE), 
	"READCOUNT" NUMBER, 
	"USERID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIMPLEBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SIMPLEBOARD_PK" ON "HR"."SIMPLEBOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SIMPLEBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."SIMPLEBOARD" ADD CONSTRAINT "SIMPLEBOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SIMPLEBOARD" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SIMPLEBOARD
--------------------------------------------------------

  ALTER TABLE "HR"."SIMPLEBOARD" ADD CONSTRAINT "SIMPLEBOARD_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "HR"."MEMBERDB" ("USERID") ENABLE;
